audio_alsaops: fix format conversion error handling bug
Returns a invalid format after fatal error,
instead of "0", which equals to PCM_FORMAT_S16_LE or
AUDIO_FORMAT_DEFAULT.

Also fix below build error:
hardware/libhardware/include/hardware/audio_alsaops.h:63:16:
error: cannot initialize return object of type 'enum pcm_format' with an rvalue of type 'int'
        return 0;
hardware/libhardware/include/hardware/audio_alsaops.h:97:16:
error: cannot initialize return object of type 'audio_format_t' with an rvalue of type 'int'
        return 0;

Signed-off-by: Jindong <jindong.yue@nxp.com>
Change-Id: Iabf5ae106d9c371c00ad5236326c6f38d1a9f116